version: "2.12"

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - BROKER_URI=redis://redis
            - BACKEND_URI=redis://redis
        depends_on:
            - worker
            - redis
        volumes:
            -   ./jobs:/counter_sairus/jobs
    worker:
        container_name: celery
        environment:
            - HDFS_HOST=172.20.0.4      # Replace this with the IP address of the hadoop container
            - HDFS_PORT=9870            # Replace the port with the one hadoop is listening on
            - BROKER_URI=redis://redis
            - BACKEND_URI=redis://redis
        build:
            context: .
            dockerfile: Dockerfile_worker
        depends_on:
            - redis
        volumes:
            -  ./jobs:/counter_sairus/jobs
    redis:
        image: "redis:alpine3.17"
        ports:
            - 6379
