FROM python:3.8.16-bullseye
RUN apt-get install ca-certificates
RUN update-ca-certificates
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . .
# RUN wget -O /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x /usr/local/bin/wait-for-it.sh
CMD ["celery", "-A", "task_manager.worker.celery", "worker", "--loglevel", "debug"]

