FROM python:3.8.16-bullseye
RUN apt-get install ca-certificates
RUN update-ca-certificates
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . ./counter_sairus
WORKDIR /counter_sairus
CMD ["celery", "-A", "task_manager.worker.celery", "worker", "--loglevel", "debug"]

