version: "3.8"

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            -   5000:5000
        volumes:
            - "./jobs/:/jobs"
        depends_on:
            - redis

    redis:
        container_name: redis
        image: "redis:alpine"
        expose:
            -   6379
