dataset_general_params:
  dir_graph: "dataset/big_dataset/graph"
  train_df: "dataset/big_dataset/train.csv"
  field_id: "id"
  field_text: "text_cleaned"
  field_label: "label"
train_dataset_params:
  train_social_net: "dataset/big_dataset/graph/social_network_train.edg"
  train_spatial_net: "dataset/big_dataset/graph/spatial_network_train.edg"
  consider_content: True
  consider_rel: True
  consider_spat: True
test_dataset_params:
  test_df: "dataset/anthony/tweets.csv"
  test_social_net: "dataset/anthony/graph/social_network.edg"
  test_spatial_net: "dataset/anthony/graph/spatial_network.edg"
  consider_content: True
  consider_rel: True
  consider_spat: True

model_params:
  dir_models: "dataset/test"
  epochs_rel: 25
  epochs_spat: 25
  mlp_batch_size: 64
  mlp_lr: 3e-1
  ne_dim_rel: 256
  ne_dim_spat: 128
  ne_technique_rel: "graphsage"
  ne_technique_spat: "graphsage"
  word_emb_size: 128
  w2v_epochs: 15