dataset_general_params:
  embedding: "sonar"
  dir_graph: "dataset/GAB_dataset/synthetic"
  train_df: "dataset/GAB_dataset/synthetic/train.tsv"
  field_id: "account_id"
  field_text: "posts"
  field_label: "binary_label"
  real_synthetic: "synthetic"
train_dataset_params:
  train_social_net: "dataset/GAB_dataset/synthetic/train_network.edg"
  consider_content: True
  consider_rel: False
  consider_spat: False
  separator: "\t"
  retrain: False
test_dataset_params:
  test_df: "dataset/GAB_dataset/synthetic/test.tsv"
  test_social_net: "dataset/GAB_dataset/synthetic/test_network.edg"
  consider_content: True
  consider_rel: False
  consider_spat: False
  separator: "\t"


model_params:
  dir_models: "dataset/GAB_dataset/models"
  epochs_rel: 25
  epochs_spat: 25
  mlp_batch_size: 64
  mlp_lr: 4e-1
  ne_dim_rel: 128
  ne_dim_spat: 128
  word_emb_size: 128
  w2v_epochs: 15
  loss: "none"